"""Build v2 dashboard without changing v1 dated archives."""
from pathlib import Path
import html,json
import entry_score as es
ROOT=Path(__file__).resolve().parents[1];D=ROOT/'dist';DB=ROOT.parent/'leader-case-db'
E=lambda v:html.escape(str(v),quote=True)
N=lambda v:'—' if v is None else f'{v:,.0f}'
P=lambda v:'—' if v is None else f'{v:+.1%}'
paths=sorted((DB/'monitoring-entry-v2-liquidity100').glob('*/snapshot.json'));assert paths,'Collect v2 first'
a=json.loads(paths[-1].read_text(encoding='utf-8'));assert a['score_version']==es.VERSION
initial=not a.get('previous_asof');changes=a['changes'];cfg=es.CONFIG
selected=sorted([r for r in a['metrics'] if r['pool']!='outside'],key=lambda r:(r['pool']!='candidate',-r['priority_score'],r['code']))
columns=[('score','진입 적합도'),('delta','점수 변화'),('close','기준 종가'),('min','검토 하한'),('max','검토 상한'),('stop','실패 기준'),('risk','실패선 거리'),('cap','시총 (억원)'),('rs20','RS20'),('liquidity','최근 3일 최대 거래대금 (억원)'),('volume','거래량 배수')]
headers='<th>종목 · 판단</th>'+''.join(f'<th aria-sort="{"descending" if k=="score" else "none"}"><button class="sort-button" data-sort="{k}" data-label="{label}">{label} <span>{"▼"if k=="score"else"↕"}</span></button></th>'for k,label in columns)+'<th>진입 장면 · 보류 이유</th>'
rows=[]
for r in selected:
 e=r['entry'];vals=dict(score=r['priority_score'],delta=r.get('score_delta'),close=r['close'],min=e['entry_min'],max=e['entry_max'],stop=e['failure_price'],risk=e['risk_fraction'],cap=r['cap'],rs20=r['rs20'],liquidity=r['turnover_filter']['max_krw'],volume=e['volume_ratio50'])
 attrs=' '.join(f'data-{k}="{v if v is not None else ""}"'for k,v in vals.items())
 setup={'breakout':'60일 고점 돌파','rebreakout':'조정 후 재돌파','none':'장면 대기'}[e['setup']]
 detail=' · '.join(f'{k} {v:.1f}'for k,v in e['components'].items());flow=a.get('flows',{}).get(r['code'],{}).get('periods',{}).get('20',{}).get('largest_net_buyer')
 reason=' / '.join(e['blockers'])or'가격 범위 안에서 진입 검토 · 주문 전 재확인'
 delta='—'if vals['delta'] is None else f'{vals["delta"]:+.2f}'
 cells=[f'<a href="{E(r["source"])}" target="_blank" rel="noopener noreferrer">{E(r["name"])}</a><small>{r["market"]} · {r["code"]}</small><b class="entry-state">{E(r["state"])}</b>',f'{r["priority_score"]:.2f}',delta,N(r['close']),N(e['entry_min']),N(e['entry_max']),N(e['failure_price']),P(e['risk_fraction']),N(r['cap']/1e8),P(r['rs20']),f'{r["turnover_filter"]["max_krw"]/1e8:,.1f}',f'{e["volume_ratio50"]:.2f}배',f'<b>{setup}</b><small>{e["signal_date"]or"최근 3거래일 신호 없음"}</small><p>{E(reason)}</p><details><summary>점수 근거·수급</summary><p>{E(detail)}</p><p>20일 최다 순매수: {E(flow or "미확인")} (수량 기준·점수 미반영)</p><p>수정주가 기반 계산 참고가격 · 호가 단위 조정 전</p></details>']
 rows.append(f'<tr data-pool="{r["pool"]}" data-change="{r.get("change","baseline")}" data-market="{r["market"]}" data-name="{E(r["name"]+" "+r["code"])}" data-state="{E(r["state"])}" {attrs} {"hidden"if r["pool"]!="candidate"else""}>'+''.join(f'<td class="{"entry-reason"if i==12 else "priority-score"if i==1 else ""}">{v}</td>'for i,v in enumerate(cells))+'</tr>')
calpath=DB/'entry-calibration/final.v1.json';cal=json.loads(calpath.read_text(encoding='utf-8'))if calpath.exists()else None
caltext=f"100억원 필터 적용 전 기준: 기존 14사례 매수 {cal['targets']}건 중 판단일 당일 {cal['matched']}건 포착 ({cal['matched']/cal['targets']:.1%}). 이 사례로 기준을 조정한 재현율이며 미래 성과가 아닙니다. 새 거래대금 필터 적용 후의 재현율은 별도 검증 전입니다."if cal else '과거 진입 시점 재현 검증 중'
options=''.join(f'<option>{E(x)}</option>'for x in sorted({r['state']for r in selected}))
comparison='새 점수 첫 기준 기록 · 이전 관찰 점수와의 증감은 계산하지 않습니다.'if initial else f"직전 성공 기록 {a['previous_asof']} 대비 · 같은 점수 버전끼리 비교"
cards=''.join(f'<button data-view="{key}"><span>{label}</span><b>{value}</b></button>'for key,label,value in [('candidate','진입 검토',a['counts']['candidate']),('new','새로 조건 충족','—'if initial else len(changes['new'])),('rising','진입 점수 상승','—'if initial else len(changes['rising'])),('watch','대기·보류 관찰군',a['counts']['watch'])])
page=f'''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="snapshot-date" content="{a['asof']}"><meta name="score-version" content="{es.VERSION}"><title>진입 검토 후보 · 주도주 레이더</title><link rel="stylesheet" href="style.css"><link rel="stylesheet" href="screening.css"><link rel="stylesheet" href="monitor.css?v=entry2"><script src="cloud-monitor.js?v=entry2" defer></script></head><body><header><a class="brand" href="index.html">↗ 주도주 레이더</a><a class="library-button" href="case-library.html">Case Library ↗</a></header><main>
<div class="monitor-heading"><div><div class="eyebrow">ENTRY READINESS</div><h1>지금 진입을 검토할 종목</h1><p>{a['asof']} 종가 기준 · 개장일 16:00 클라우드 점검 · 장중 가격 아님</p></div><a href="#monitor-method">새 점수 기준</a></div><p class="entry-notice"><b>‘진입 검토’는 기준일 종가에서 조건을 충족했다는 뜻입니다.</b> 다음 거래일 검토 상한 초과·실패 기준 이탈 시 보류합니다. 실패선 거리는 보장된 최대손실이 아닙니다.</p>
<p class="comparison-note"><b>시총 1,000억원 이상 · 최근 3거래일 중 하루라도 실제 거래대금 100억원 초과</b> · 미충족 종목은 후보·관찰군에서 제외</p><div class="monitor-stats">{cards}</div><p class="comparison-note">{comparison}</p><section id="all-candidates"><div class="controls"><label>보기<select id="screen-view"><option value="candidate">진입 검토</option><option value="new">새로 조건 충족</option><option value="rising">진입 점수 상승</option><option value="watch">대기·보류 관찰군</option></select></label><label>종목명·코드<input id="screen-search" type="search" placeholder="종목명 또는 코드"></label><label>시장<select id="screen-market"><option value="">전체</option><option>KOSPI</option><option>KOSDAQ</option></select></label><label>판단 상태<select id="screen-state"><option value="">전체</option>{options}</select></label><span id="screen-count" aria-live="polite">{a['counts']['candidate']}개</span></div><p id="screen-sort-status" class="sort-status" role="status">정렬: 진입 적합도 · 높은 순</p><p class="sort-help">가격은 원 단위 계산 참고값 · 열 제목을 눌러 정렬</p><div class="table-scroll" tabindex="0" role="region" aria-label="진입 검토 표 좌우 스크롤"><table id="candidate-table"><thead><tr>{headers}</tr></thead><tbody>{''.join(rows)}</tbody></table></div><p id="screen-empty" hidden>조건을 충족한 종목이 없습니다. 관찰군에서 대기·보류 이유를 확인하세요.</p></section>
<details class="scope" id="monitor-method"><summary>점수 기준 · 과거 재현율 · 자료 범위</summary><p>{caltext}</p><p>전체 일반 주식 {a['counts']['common']:,}개 중 시총 1,000억원 이상 {a['counts'].get('cap1000',0):,}개와 직전 관찰군을 매번 다시 조사합니다. 시총 증가는 증자 등의 영향일 수도 있습니다.</p><ul><li>100점 배점: 진입 장면 35, 추세 확인 20, 거래 확인 15, 실패 기준 거리 20, 추격 부담 10. 수익 확률이 아닙니다.</li><li>돌파: 직전 60거래일 최고 종가 초과 + 직전 50일 평균 대비 거래량 1.5배. 재돌파: 추적 중인 고점에서 10% 이상 조정한 뒤 그 고점 회복. 최근 180거래일에서 순차 감지하며 조정은 120거래일까지 추적합니다.</li><li>신호 포함 3거래일 안의 장면만 유효. 20일선 상회·RS20 양수, 점수 {cfg['min_score']} 이상과 가격·유동성 조건을 모두 통과해야 진입 검토. 조건 미달이면 점수는 최대 59점이고 이유를 표시합니다.</li><li>추가 제외 조건: 최근 3거래일 실제 거래대금 최댓값이 100억원을 초과해야 합니다. 정확히 100억원은 미통과. 휴장일 제외, 합계·평균 기준 아님. 미확인 자료는 0으로 간주하지 않으며 통과 확인 전까지 제외합니다. 공급자 제공 거래대금을 사용하며 종가×거래량으로 대체하지 않습니다.</li><li>기존 점수 내부 거래대금 근사치: 20일 종가×거래량 중앙값 {cfg['min_liquidity']/1e8:.0f}억원 이상 또는 최근 5일 평균이 기준 이상이면서 3일 이상 기준 충족.</li><li>실패 기준 = 신호 전 10일 최저 종가와 (돌파 기준−20일 평균 변동폭) 중 높은 값. 검토 상한 = 돌파 기준+{cfg['max_pivot_atr']}배 변동폭, 신호일 20일선+{cfg['max_ma_atr']}배 변동폭, 실패 기준 거리 {cfg['max_risk']:.0%} 한도 가격 중 최저값. 신호일 기준을 고정합니다. 8% 초과는 고변동 조건부로 구분합니다.</li><li>마지막 성공 수집일의 종가 기준이며 장중 주문 지시가 아닙니다. 데이터 누락은 0점이나 이탈로 단정하지 않습니다. 81일 이력 부족·현재 무거래·현재 정지 종목은 계산 제외합니다.</li><li>텔레그램은 현재 진입 검토 종목 중 같은 버전 점수 상승 상위 3개를 요약하고 새 조건 충족을 별도 표시합니다. 버전 변경일에는 상승 순위를 만들지 않습니다.</li></ul><p>20일 개인·기관·외국인 수급은 진입 검토 상위 60개·관찰군 상위 40개에 보조 제공하며, 미확인은 0을 뜻하지 않습니다. 가격 검토 제외 {len(a['errors'])}개.</p><p><a href="monitor-latest.json" download>현재 판단 기록 내려받기</a> · <a href="entry-validation.html">14사례 진입 재현 상세</a> · <a href="case-library.html">과거 사례</a></p></details></main></body></html>'''
D.mkdir(parents=True,exist_ok=True);(D/'index.html').write_text(page,encoding='utf-8')
public={k:v for k,v in a.items()if k not in ('listing','metrics')};public.update(candidates=[r for r in selected if r['pool']=='candidate'],watch=[r for r in selected if r['pool']=='watch'])
(D/'monitor-latest.json').write_text(json.dumps(public,ensure_ascii=False,indent=2),encoding='utf-8')
print('Entry dashboard:',a['counts'])
