"""Build the current dashboard without rewriting dated screening/research archives."""
from pathlib import Path
import html,json,re
ROOT=Path(__file__).resolve().parents[1];D=ROOT/'dist';DB=ROOT.parent/'leader-case-db'
E=lambda x:html.escape(str(x),quote=True)
N=lambda x:f'{x:,.0f}' if x is not None else '—'
P=lambda x:f'{x*100:+.1f}%' if x is not None else '—'
snapshots=sorted((DB/'monitoring').glob('*/snapshot.json'));assert snapshots,'Run monitor_market.py first'
a=json.loads(snapshots[-1].read_text(encoding='utf-8'));changes=a['changes'];initial=not a['previous_asof']
library_path=D/'case-library.html'
if not library_path.exists():
 old=(D/'index.html').read_text(encoding='utf-8');library=re.search(r'<section id="case-library".*?</section>',old,re.S);assert library
 library_path.write_text('<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Case Library · 주도주 레이더</title><link rel="stylesheet" href="style.css"><link rel="stylesheet" href="case.css"></head><body><header><a class="brand" href="index.html">↗ 주도주 레이더</a><a href="index.html">현재 후보군으로</a></header><main>'+library.group(0)+'</main></body></html>',encoding='utf-8')
for p in (D/'cases').glob('*.html'):
 text=p.read_text(encoding='utf-8').replace('../index.html#case-library','../case-library.html');p.write_text(text,encoding='utf-8')
# Preserve old external links to the library via the root hash redirect.
rows=[];selected=sorted([r for r in a['metrics'] if r['pool']!='outside'],key=lambda r:-r['priority_score'])
columns=[('score','관찰 점수'),('delta','점수 변화'),('cap','시총 (억원)'),('close','종가'),('rs20','RS20'),('rs60','RS60'),('liquidity','20일 거래대금 (근사·억원)'),('acceleration','5일 거래 증가'),('distance','20일선 이격'),('drawdown','60일 고점 대비'),('netbuy','20일 최다 순매수 (주)'),('buydays','순매수 일수')]
headers='<th>종목</th>'+''.join(f'<th aria-sort="{"descending" if k=="score" else "none"}"><button type="button" class="sort-button" data-sort="{k}" data-label="{label}" aria-label="{label}: {"낮은 순" if k=="score" else "높은 순"} 정렬">{label} <span aria-hidden="true">{"▼" if k=="score" else "↕"}</span></button></th>' for k,label in columns)+'<th>가격 상태</th>'
for r in selected:
 f=a['flows'].get(r['code'],{}).get('periods',{}).get('20',{});who=f.get('largest_net_buyer');g=f.get('groups',{}).get(who,{})
 values=dict(score=r['priority_score'],delta=r['score_delta'],cap=r['cap'],close=r['close'],rs20=r['rs20'],rs60=r['rs60'],liquidity=r['median_value20_proxy'],acceleration=r['value_acceleration'],distance=r['distance_ma20'],drawdown=r['drawdown60'],netbuy=g.get('net_shares'),buydays=g.get('buy_days'))
 attrs=' '.join(f'data-{k}="{v if v is not None else ""}"' for k,v in values.items())
 badge='비교 대기' if initial else {'new':'신규 편입','new_unverified':'신규 여부 확인 중','rising':'점수 상승'}.get(r['change'],'유지')
 delta='—' if r['score_delta'] is None else f'{r["score_delta"]:+.2f}'
 flow=(E(who)+'<small>'+N(g.get('net_shares'))+'주</small>') if who else '순매수 주체 없음' if f and all(x.get('net_shares') is not None for x in f.get('groups',{}).values()) else '미확인'
 rows.append(f'<tr data-pool="{r["pool"]}" data-change="{r["change"]}" data-market="{r["market"]}" data-name="{E(r["name"]+" "+r["code"])}" data-state="{E(r["state"])}" {attrs} {"hidden" if r["pool"]=="watch" else ""}><td><a href="{E(r["source"])}" target="_blank" rel="noopener noreferrer">{E(r["name"])}</a><small>{r["market"]} · {r["code"]}</small><span class="change-tag">{badge}</span></td><td class="priority-score">{r["priority_score"]:.2f}</td><td class="delta">{delta}</td><td>{N(r["cap"]/1e8)}</td><td>{N(r["close"])}</td><td>{P(r["rs20"])}</td><td>{P(r["rs60"])}</td><td>{r["median_value20_proxy"]/1e8:,.1f}</td><td>{r["value_acceleration"]:.2f}배</td><td>{P(r["distance_ma20"])}</td><td>{P(r["drawdown60"])}</td><td>{flow}</td><td>{N(g.get("buy_days"))} / 20</td><td>{r["state"]}</td></tr>')
def eventlist(key,empty):
 entries=changes[key]
 return '<ul>'+''.join('<li><b>'+E(r['name'])+'</b> · '+E(r.get('reason') or ('정식 후보' if r.get('pool')=='candidate' else '추가 조건 확인'))+'</li>' for r in entries)+'</ul>' if entries else '<p>'+('첫 기록 · 비교 대기' if initial else empty)+'</p>'
new='—' if initial else str(len(changes['new']));rising='—' if initial else str(len(changes['rising']));comparison='첫 비교 기준 기록 · 다음 개장일 기록부터 신규 편입과 점수 변화를 표시합니다.' if initial else f'직전 저장일 {a["previous_asof"]} 대비 · 누락된 거래일이 있으면 하루 변화와 다를 수 있습니다.'
state_options=''.join('<option>'+E(s)+'</option>' for s in sorted({r['state'] for r in selected}))
page=f'''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>현재 주도주 후보 · 주도주 레이더</title><meta name="description" content="주도주 후보의 신규 편입, 점수 변화와 시가총액 4천억~5천억원 예비 후보를 추적합니다."><link rel="stylesheet" href="style.css"><link rel="stylesheet" href="screening.css?v=monitor1"><link rel="stylesheet" href="monitor.css"><script src="screening.js?v=monitor1" defer></script></head><body><header><a class="brand" href="index.html"><span class="brandmark">↗</span> 주도주 레이더</a><a class="library-button" href="case-library.html">Case Library ↗</a></header><main><div class="monitor-heading"><div><div class="eyebrow">LEADER WATCH</div><h1>현재 주도주 후보군</h1><p>{a['asof']} 종가 기준 · 매 개장일 16:00 점검 예정</p></div><a href="#monitor-method">선정·변화 기준</a></div>
<div class="monitor-stats"><button data-view="candidate"><span>정식 후보</span><b>{a['counts']['candidate']}</b></button><button data-view="new"><span>신규 편입</span><b>{new}</b></button><button data-view="rising"><span>점수 상승</span><b>{rising}</b></button><button data-view="watch"><span>4천억~5천억 예비 후보</span><b>{a['counts']['watch']}</b></button></div><p class="comparison-note">{comparison}</p>
<section id="all-candidates"><div class="controls"><label>보기<select id="screen-view"><option value="candidate">정식 후보</option><option value="new">신규 편입</option><option value="rising">점수 상승</option><option value="watch">예비 후보 · 시총 4천억~5천억</option></select></label><label>종목명·코드<input id="screen-search" type="search" placeholder="종목명 또는 코드"></label><label>시장<select id="screen-market"><option value="">전체</option><option>KOSPI</option><option>KOSDAQ</option></select></label><label>가격 상태<select id="screen-state"><option value="">전체</option>{state_options}</select></label><span id="screen-count" aria-live="polite">{a['counts']['candidate']}개</span></div><p id="screen-sort-status" class="sort-status" role="status">정렬: 관찰 점수 · 높은 순</p><p class="sort-help">열 제목으로 높은 순·낮은 순 정렬 · 예비 후보는 정식 편입 전 관찰 대상입니다.</p><div class="table-scroll" tabindex="0" role="region" aria-label="후보 목록 · 좌우 스크롤"><table id="candidate-table"><thead><tr>{headers}</tr></thead><tbody>{''.join(rows)}</tbody></table></div><p id="screen-empty" hidden>{'아직 비교 기록이 없습니다. 다음 기록부터 변화를 표시합니다.' if initial else '해당 조건의 후보가 없습니다.'}</p></section>
<section class="monitor-events"><article><h2>시총 5,000억원 신규 진입</h2>{eventlist('cap_crossings','이번 비교에서 새로 기준을 넘은 종목이 없습니다.')}</article><article><h2>정식 후보 조건 이탈</h2>{eventlist('exits','이번 비교에서 조건 이탈이 없습니다.')}</article><article><h2>자료 확인 필요</h2>{eventlist('unknown','누락으로 인한 편입·이탈 판정 보류가 없습니다.')}</article></section>
<details class="scope" id="monitor-method"><summary>선정 기준 · 점수 변화 · 갱신 안내</summary><p>전체 종목 목록을 매번 새로 조회합니다. 현재 일반 주식 분류 {a['counts']['common']:,}개 중 시총 4,000억원 이상 {a['counts']['cap4000']}개를 가격 검토 대상으로 삼고, 직전 후보는 시총이 낮아져도 추적합니다.</p><ul><li>정식 후보: 시총 5,000억원 이상, 최근 20일 중앙 종가×거래량 50억원 이상, 20일 또는 60일 상대강도 양수 및 상위 20%.</li><li>예비 후보: 시총 4,000억~5,000억원 미만에 나머지 조건 충족. 기존 정식 후보와 같은 시장의 시총·유동성 통과 집단을 기준으로 상대강도와 점수를 계산합니다. 예비 후보 추가로 기존 점수가 바뀌지 않습니다.</li><li>시총 4,000억원 미만 종목도 매번 전체 목록에서 다시 조회하므로 이후 기준을 넘으면 검토 대상에 들어옵니다. 시총 기준 신규 진입과 정식 후보 신규 편입은 별개입니다.</li><li>점수 변화 = 현재 점수 − 직전 저장일 점수. 같은 점수 산식일 때만 비교하며, 모든 상승을 표에 표시하고 +5점 이상은 주요 변화로 알립니다. 시장 구성 변화도 순위와 점수에 영향을 줍니다.</li><li>자료 누락은 조건 이탈로 처리하지 않습니다. 시총 증가는 주가뿐 아니라 증자 등 기업행동 때문일 수도 있습니다. 신규 편입·상승 점수는 자동 매수 신호가 아닙니다.</li><li>점수 배점: RS20 순위 40, RS60 순위 25, 순위 개선 10, 거래 확대 10, 20일선 위 10, 20일선 상승 5, 과열 −15. 아직 검증 전 가설이며 실적·수급은 이 점수에 포함되지 않습니다.</li><li>개장일 오후 4시(한국시간)에 점검합니다. 사이트는 마지막 성공한 게시 기록을 보여주며 실시간 시세가 아닙니다. 수집 또는 게시 실패 시 이전 기록을 유지합니다. 실제 점검에는 연결된 작업 환경과 데이터 접근이 필요합니다.</li></ul><p>20일 최다 순매수는 개인·기관·외국인 중 수량 기준입니다. 실제 거래대금·기업행동·종목 원장에 대한 독립 검증은 미완료입니다. 이번 가격 검토 제외 {len(a['errors'])}개: {E(' · '.join(r['name']+'('+r['error']+')' for r in a['errors']))}</p><p><a href="monitor-latest.json" download>현재 후보와 변화 기록 내려받기</a> · <a href="screening-2026-09-23.html#reviewed">2026-09-23 기준 사업 근거 검토 6개</a> · <a href="case-library.html">과거 사례 보기</a></p></details></main></body></html>'''
(D/'index.html').write_text(page,encoding='utf-8')
public={k:v for k,v in a.items() if k not in ['listing','metrics']};public['candidates']=[r for r in selected if r['pool']=='candidate'];public['watch']=[r for r in selected if r['pool']=='watch']
(D/'monitor-latest.json').write_text(json.dumps(public,ensure_ascii=False,indent=2),encoding='utf-8')
# Dated older screen continues to work; library navigation now opens the separate page.
for p in D.glob('screening-*.html'):
 p.write_text(p.read_text(encoding='utf-8').replace('href="index.html#case-library"','href="case-library.html"'),encoding='utf-8')
print(f'Dashboard: {a["counts"]["candidate"]} candidates, {a["counts"]["watch"]} watch; baseline={initial}')
